name: Release

on:
  # Trigger the workflow on the new 'v*' tag created
  push:
    tags:
      - "v*"

jobs:
  create_release:
    name: Create Github Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

  build_artifact:
    needs: [create_release]
    name: ${{ matrix.os }}/GHC ${{ matrix.ghc }}/${{ github.ref }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc:
          - "8.8.4"
        cabal: ["3.2"]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Haskell
        uses: haskell/actions/setup@v2.0.1
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Freeze
        run: |
          cabal freeze

      - name: Cache ~/.cabal/store
        uses: actions/cache@v3.0.11
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build binary
        run: |
          mkdir dist
          cabal install --install-method=copy --overwrite-policy=always --installdir=dist

      - name: Set writings binary path name
        run: echo "WRITINGS_BINARY_PATH=./dist/ai-writings" >> $GITHUB_ENV

      - name: Set readings binary path name
        run: echo "READINGS_BINARY_PATH=./dist/ai-readings" >> $GITHUB_ENV

      - name: Compress writings binary
        uses: svenstaro/upx-action@2.0.1
        with:
          file: ${{ env.WRITINGS_BINARY_PATH }}

      - name: Compress readings binary
        uses: svenstaro/upx-action@2.0.1
        with:
          file: ${{ env.READINGS_BINARY_PATH }}

      - name: Upload Release Asset Writings
        id: upload-release-asset-writing
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ env.WRITINGS_BINARY_PATH }}
          asset_name: ai-writings-${{ runner.os }}-ghc-${{ matrix.ghc }}
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Readings
        id: upload-release-asset-readings
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ env.READINGS_BINARY_PATH }}
          asset_name: ai-readings-${{ runner.os }}-ghc-${{ matrix.ghc }}
          asset_content_type: application/octet-stream